DROP TABLE IF EXISTS PRODUCTS;
  
CREATE TABLE PRODUCTS (
  sku INT AUTO_INCREMENT  PRIMARY KEY,
  brand VARCHAR(250) NOT NULL,
   price VARCHAR(250) NOT NULL,
   color VARCHAR(250) NOT NULL,
   size VARCHAR(250) NOT NULL,
   availableProductsFromSeller VARCHAR(250) NOT NULL
);