DROP TABLE IF EXISTS PRODUCTS_TABLE;
  
CREATE TABLE PRODUCTS_TABLE (
  skuNumber INT AUTO_INCREMENT  PRIMARY KEY,
  brandName VARCHAR(250) NOT NULL,
   priceOfArticle VARCHAR(250) NOT NULL,
   colorOfArticle VARCHAR(250) NOT NULL,
   sizeOfArticle VARCHAR(250) NOT NULL,
   availableProductsFromSeller VARCHAR(250) NOT NULL
);